#!/usr/bin/env bash

prefix="vcw_module_hkvb_dotnet_aspnet__$1"
prefix="vcw_module_hkvb_dotnet_aspnet__$1"

if [[ "vcw_module_hkvb_dotnet_aspnet__dotnet_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create vcw_module_hkvb_dotnet_aspnet__dotnet_volume
fi
