---
version: '3'
services:

# START SERVICE hkvb/dotnet/aspnet
  dotnetcore:
    image: ${VCW_REGISTRY}mcr.microsoft.com/dotnet/aspnet:5.0
    environment: [${DOTNET_ENVIRONMENT}]
    command: [${DOTNET_COMMAND}]
    volumes: ['${VCW_STACK_GLOBAL_STACKPREFIX}_volume:/app']
    ports: []
    networks: [${VCW_STACK_GLOBAL_NETWORKLOCAL}_overlay]
    deploy:
      mode: ${DOTNET_DEPLOY_MODE}
      resources:
        limits:
          memory: '${DOTNET_DEPLOY_RESOURCES_LIMITS_MEMORY}'
        reservations:
          memory: '${DOTNET_DEPLOY_RESOURCES_RESERVATIONS_MEMORY}'
${DOTNET_COMPOSE_EXTENSIONS}
# END SERVICE hkvb/dotnet/aspnet

networks: {${VCW_STACK_GLOBAL_NETWORKLOCAL}_overlay: { external: true }}
volumes: {${VCW_STACK_GLOBAL_STACKPREFIX}_volume: { external: true }}
${VCW_STACK_GLOBAL_COMPOSE_EXTENSIONS}
