#!/usr/bin/env bash

prefix="vcwc_dotnetcore_runtime__$1"
prefix="vcwc_dotnetcore_runtime__$1"

if [[ "vcwc_dotnetcore_runtime__dotnetcore_dotnetcore_runtime_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create vcwc_dotnetcore_runtime__dotnetcore_dotnetcore_runtime_volume
fi

if [[ "vcwc_dotnetcore_runtime__dotnetcore_dotnetcore_runtime_volume" == "$prefix"* ]] ; then
	executionplane --silent docker run -v vcw_controlplane_repos:/source -v vcwc_dotnetcore_runtime__dotnetcore_dotnetcore_runtime_volume:/app ${VCW_REGISTRY}hkvb/controlplane.vcw console cmd tar -C / -xvf /source/hkvb/dotnetcore/runtime/_module/volumes/dotnetcore_dotnetcore_runtime_volume.tar
fi
